### ISSUE TITLE
Bot doesn't detect players over max_apm

### ISSUE THREAD

**Issue by Lgreenbunny** [tetrio-community/autohost#70]
I had a lobby around 6-7 pm EDT/EST today where several people went over the max_apm set and nothing happened to them. The setting worked the last time I tried it a day or two ago, and I've only used the setting in two lobbies so I'm not sure if this happens often.

**Comment by ZudoB** [comment]
Going to leave this issue open, as I'm still trying to figure out the best way to implement this.

I've clarified the way APM limits work, so take a look at https://kagar.in/autohost/apm

**Comment by ZudoB** [comment]
Moved to https://gitlab.com/Zudo/autohost/-/issues/70
