### ISSUE TITLE
Room Creation not working right

### ISSUE THREAD

**Issue by orangetriangle** [tetrio-community/autohost#74]
After creating one Autohost room, I cannot seem to create a second one.
![image](https://user-images.githubusercontent.com/77557642/120053805-3eb96a00-bffa-11eb-8640-c82c2d5d5624.png)

**Comment by ZudoB** [comment]
Fixed in 9fa518876dd58fb21443f9c836e6543a1194da2c, there was a server update that didn't disconnect the previous instances, which I hadn't accounted for.
