### ISSUE TITLE
Bot lets player know total infractions for max_APM

### ISSUE THREAD

**Issue by Lgreenbunny** [tetrio-community/autohost#75]
Would it be possible to let the players know how many infractions they have from going over the APM for that rule? I think I heard like 3 people today asking about that or so. Maybe it could be through direct messages so it won't clog the chat with big rooms.

**Comment by ZudoB** [comment]
This won't be too hard to implement. I'd like to adjust the infractions somewhat to avoid false positives, will factor that in at the same time.
