### ISSUE TITLE
Unranked players are allowed in ranked rooms

### ISSUE THREAD

**Issue by sjl** [tetrio-community/autohost#85]
Rooms like `SS AND BELOW ONLY` are supposed to only allow players of a given rank or less.  Anonymous users are correctly moved to spectators, but unranked players are allowed:

![screenshot_2021-06-09_23-44-55](https://user-images.githubusercontent.com/58365/121461441-dc0e8980-c97c-11eb-89bc-24a31b9e51f5.png)

Unranked players should be moved to spectators as well to prevent smurfing.

**Comment by RedStone576** [comment]
I mean `minimum_rank` rule exists but that room is for everyone below SS, also I'm pretty sure that room already has an APM limiter

**Comment by ZudoB** [comment]
There are APM limits for these rooms, which should catch out most smurfs. If you do see someone in particular doing this, let me know so I can check.

The rules of these rooms are subject to change, and recently I blocked guest players from these rooms to avoid an influx of smurfs.
